
apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service
  namespace: production
  labels:
    app: payment-service
    team: payments

spec:
  replicas: 3

  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service

    spec:
      containers:
        - name: api
          image: payments-api:1.4.2
          ports:
            - containerPort: 8000

        - name: metrics
          image: prom/statsd-exporter:v0.26.1
          ports:
            - containerPort: 9102

        - name: log-agent
          image: fluent/fluent-bit:3.1.4
